application: kritikosbot-telegram
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on
- deferred: on

handlers:
- url: /set_webhook
  login: admin
  script: main.app

- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: .*
  script: main.app

- url: /html
  static_dir: html
  application_readable: true

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest



